# Generated by Django 6.0.2 on 2026-02-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('status', models.CharField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('order', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('purpose', models.TextField()),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('nights', models.IntegerField()),
                ('days', models.IntegerField()),
                ('destination', models.TextField()),
                ('distance_full', models.FloatField()),
                ('total', models.FloatField()),
                ('stage_id', models.IntegerField()),
                ('status', models.CharField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.IntegerField()),
                ('allowance_id', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('surname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.TextField()),
                ('department', models.CharField(choices=[('FINANCE', 'Finance'), ('HUMAN_RESOURCES', 'Human Resources'), ('ENGINEERING', 'Engineering')], default='FINANCE', max_length=20)),
                ('position', models.CharField(choices=[('AUDITOR', 'Auditor'), ('ENGINEER', 'Engineer'), ('DRIVER', 'Driver')], default='AUDITOR', max_length=20)),
                ('grade', models.CharField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1, max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('status', models.CharField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, max_length=1)),
            ],
        ),
    ]
