# Generated by Django 6.0.2 on 2026-03-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tns_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstage',
            name='status',
        ),
        migrations.AlterField(
            model_name='approvalstage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
