# Generated by Django 6.0.2 on 2026-03-09 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tns_api', '0002_remove_approvalstage_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='distance_full',
            new_name='calculated_distance',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='arrival_date',
        ),
        migrations.AddField(
            model_name='claim',
            name='origin',
            field=models.TextField(default='here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='user_distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='departure_date',
            field=models.DateTimeField(),
        ),
    ]
