# Generated by Django 6.0.2 on 2026-03-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tns_api', '0006_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstage',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='approval_stages', to='tns_api.employee'),
        ),
    ]
