# Generated by Django 6.0.2 on 2026-03-16 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tns_api', '0007_approvalstage_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='tns_api.claimline')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
