# Generated by Django 6.0.2 on 2026-03-16 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tns_api', '0008_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('base_distance_km', models.FloatField()),
                ('adjusted_distance_km', models.FloatField()),
                ('errands_factor', models.FloatField(default=1.2)),
                ('source', models.CharField(default='nominatim', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gps_validation', to='tns_api.claim')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
