# Generated by Django 6.0.2 on 2026-03-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tns_api', '0009_gpsvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='actual_mileage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
