# Generated by Django 6.0.2 on 2026-03-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tns_api', '0012_claim_documents_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thresholdconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
